config-version: 1
root-folder: './migrations'
modules-folder: null
connections-file-path: './connections.toml'
connection-name: snowflake
change-history-table: CHANGE_HISTORY
create-change-history-table: true
autocommit: false
verbose: true
dry-run: false
query-tag: 'schemachange'
