config-version: 1
root-folder: './migrations/dev'
modules-folder: null
connections-file-path: './connections.toml'
connection-name: snowflake
change-history-table: "APP_DB.DEV.SCHEMACHANGE_HISTORY"
create-change-history-table: true
autocommit: false
verbose: true
dry-run: false
query-tag: 'schemachange-dev'
