name: Deploy to Snowflake with Schemachange

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: snowflake-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-dev:
    name: Deploy to DEV schema
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange (DEV)
        env:
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME:  ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          schemachange --verbose -c schemachange-config/config-dev.yml

  deploy-test:
    name: Deploy to TEST schema
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange (TEST)
        env:
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME:  ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          schemachange --verbose -c schemachange-config/config-test.yml

  deploy-prod:
    name: Deploy to PROD schema
    runs-on: ubuntu-latest
    needs: deploy-test
    environment: production   # Require approval in GitHub repo settings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange (PROD)
        env:
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME:  ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:      ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          schemachange --verbose -c schemachange-config/config-prod.yml
