name: Deploy Snowflake with Schemachange

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Create connections.toml for DEV
        run: |
          cat <<EOF > connections.toml
          [snowflake]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USERNAME }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "DEV"
          EOF

      - name: Run schemachange on DEV
        run: |
          schemachange --verbose \
            -f migrations \
            -c schemachange-config/config-dev.yml

  test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Create connections.toml for TEST
        run: |
          cat <<EOF > connections.toml
          [snowflake]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USERNAME }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "TEST"
          EOF

      - name: Run schemachange on TEST
        run: |
          schemachange --verbose \
            -f migrations \
            -c schemachange-config/config-test.yml

  prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: production
      url: https://app.snowflake.com
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Create connections.toml for PROD
        run: |
          cat <<EOF > connections.toml
          [snowflake]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USERNAME }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "PROD"
          EOF

      - name: Run schemachange on PROD
        run: |
          schemachange --verbose \
            -f migrations \
            -c schemachange-config/config-prod.yml
